/* faq  —  PAGES.faq
   Merged from 1 original layer (line 2725). */
PAGES.faq=()=>`
<section class="phero"><div class="wrap">
  <span class="eyebrow">${L('Resources / FAQ','Resources / FAQ','リソース / FAQ')}</span>
  <h1>${L('Questions about product scope, AI, data, deployment, and business model.','Pertanyaan tentang product scope, AI, data, deployment, dan business model.','product scope、AI、data、deployment、business modelに関するFAQ。')}</h1>
  <p>${L('This FAQ distinguishes current product scope from roadmap/vision so external audiences do not mistake future concepts for shipped capability.','FAQ ini membedakan current product scope dari roadmap/vision agar audience eksternal tidak menganggap future concept sebagai capability yang sudah shipped.','current scopeとroadmap/visionを分離し、将来conceptを実装済みと誤認させないためのFAQです。')}</p>
</div></section>
<section class="sec"><div class="wrap"><div class="faq">
${[
  [L('Is Emenda only a chat or HR app?','Apakah Emenda hanya chat atau HR app?','Emendaはchat/HR appだけですか？'),L('No. Communication is the entry layer, but the product also covers identity, work records, follow-up, consent/privacy, analytics, notifications, organization management, and a contextual assistant.','Tidak. Communication adalah entry layer, tetapi produk juga mencakup identity, work record, follow-up, consent/privacy, analytics, notification, organization management, dan contextual assistant.','いいえ。communicationは入口で、identity、work record、follow-up、consent/privacy、analytics、notification、organization management、assistantまで含みます。')],
  [L('How many features are actually in the product catalog?','Berapa fitur yang ada di product catalog?','Product catalogには何機能ありますか？'),L('The frozen v1.0 r10 catalog records 59 approved features and 27 candidates. Candidate features are not sellable/approved scope until ruled by the Product Owner.','Katalog frozen v1.0 r10 mencatat 59 approved feature dan 27 candidate. Candidate bukan sellable/approved scope sampai diputuskan Product Owner.','v1.0 r10では59 Approved、27 Candidate。CandidateはProduct Owner判断までApproved scopeではありません。')],
  [L('What is available now versus roadmap?','Apa yang tersedia sekarang vs roadmap?','現在利用可能とroadmapの違いは？'),L('The catalog assigns features to R1–R4 and maturity labels such as MVP, Roadmap, and Vision. The website should preserve those distinctions instead of presenting the full long-term vision as already shipped.','Katalog memetakan feature ke R1–R4 dan label maturity seperti MVP, Roadmap, dan Vision. Website harus menjaga perbedaan ini.','R1–R4とMVP/Roadmap/Visionを明示し、長期visionを実装済みとして表示しません。')],
  [L('Does translation overwrite the original message?','Apakah translation mengganti pesan original?','translationは原文を上書きしますか？'),L('No. Original content is retained; translation is an additive layer. This is a core product integrity rule.','Tidak. Original content dipertahankan; translation adalah additive layer. Ini core product integrity rule.','いいえ。原文を保持しtranslationは追加layerです。')],
  [L('Can AI take actions silently?','Apakah AI dapat melakukan action diam-diam?','AIが無断でactionできますか？'),L('No for sensitive actions. Location, call, email, SMS, calendar, contacts, and similar capabilities require explicit user permission and scoped context.','Tidak untuk action sensitif. Location, call, email, SMS, calendar, contacts, dan capability serupa membutuhkan explicit user permission.','機微なactionは不可。location、call、email、SMS、calendar、contacts等は明示permissionが必要です。')],
  [L('What is the technical stack?','Apa technology stack-nya?','technical stackは？'),L('Frontend: Vite 8.2, React 19.2, TypeScript 6.0, Tailwind CSS 4.3, react-router-dom 7.18, lucide-react 1.31, recharts 3.10, sonner 2.0, oxlint 1.75, Playwright 1.62. Backend: Node.js. Database: Supabase. Hosting: Hostinger VPS. Exact backend framework/version and operational standards should be added only when formally confirmed.','Frontend: Vite 8.2, React 19.2, TypeScript 6.0, Tailwind CSS 4.3, react-router-dom 7.18, lucide-react 1.31, recharts 3.10, sonner 2.0, oxlint 1.75, Playwright 1.62. Backend: Node.js. Database: Supabase. Hosting: Hostinger VPS. Detail backend framework/version dan standard operasi ditambahkan setelah dikonfirmasi formal.','Frontend: Vite 8.2、React 19.2、TypeScript 6.0、Tailwind CSS 4.3等。Backend: Node.js、DB: Supabase、Hosting: Hostinger VPS。詳細version/運用standardは正式確認後。')],
  [L('Does the organization own the worker’s identity?','Apakah organisasi memiliki identity worker?','組織がworker identityを所有しますか？'),L('The product model separates durable worker identity from time-bound employment relationships. Employer visibility depends on relationship, purpose, permissions, and privacy rules.','Product model memisahkan durable worker identity dari time-bound employment relationship. Employer visibility bergantung relationship, purpose, permission, dan privacy rule.','durable worker identityとtime-bound employment relationshipを分離し、employer visibilityは関係・目的・権限で決まります。')],
  [L('What industries are in scope?','Industry apa yang masuk scope?','対象industryは？'),L('Caregiving is the current fixed MVP showcase. Earlier strategy documents discussed caregiving + construction cross-validation, while later MVP decisions narrowed the immediate implementation to caregiving first. Other verticals should be shown as adaptable or next-phase, not as fully shipped.','Caregiving adalah fixed MVP showcase saat ini. Dokumen strategy sebelumnya membahas caregiving + construction cross-validation, tetapi keputusan MVP berikutnya mempersempit immediate implementation ke caregiving terlebih dahulu. Vertical lain harus ditampilkan sebagai adaptable/next phase.','現在のfixed MVP showcaseは介護。以前のstrategyでは介護＋建設cross-validationを検討したが、後のMVP判断で介護優先に絞っています。')],
  [L('How does implementation start?','Bagaimana implementasi dimulai?','導入はどう始まりますか？'),L('Start with current-state discovery and one high-friction workflow, then fit-gap, configuration, required integration, controlled pilot, evaluation, and rollout. The research plan prioritizes behavioral evidence over hypothetical feature preference.','Mulai dari current-state discovery dan satu high-friction workflow, lalu fit-gap, configuration, required integration, controlled pilot, evaluation, dan rollout. Research plan memprioritaskan behavioral evidence dibanding hypothetical feature preference.','current-state discoveryとfrictionの高い1workflowから開始し、fit-gap→configuration→integration→pilot→evaluation→rollout。behavioral evidenceを優先します。')],
  [L('Where can I see the real product UI?','Di mana melihat UI produk sebenarnya?','実際のUIはどこで見られますか？'),L('Use the fixed Worker mobile Figma as the visual source of truth. Use emenda.tech for the running demo.','Gunakan fixed Worker mobile Figma sebagai visual source of truth. Gunakan emenda.tech untuk running demo.','UI正本はfixed Worker mobile Figma。動作demoはemenda.tech。')]
].map(([q,a])=>`<div class="faq-item"><button class="faq-q">${q}<span class="pm">+</span></button><div class="faq-a">${a}</div></div>`).join('')}
</div></div></section>
${detailedCTA()}`;
